// This sets the basic metadata for the site as a whole.

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CLUE-LLM",
  description:
    "Answer generated by large language models (LLMs). Double check for correctness.",
  icons: {
    icon: [
      {
        rel: "icon",
        url: "/images/cmu-scotty.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        rel: "icon",
        url: "/images/cmu-scotty-dark.png",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
